In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#pratyaksha

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIT Hackathon/temp_humid.csv")

In [ ]:
df.head()

     datetime_utc   hum   tempm
0  19961101-11:00  27.0    30.0
1  19961101-12:00  32.0    28.0
2  19961101-13:00  44.0    24.0
3  19961101-14:00  41.0    24.0
4  19961101-16:00  47.0    23.0

In [ ]:
df.isnull().sum()

datetime_utc      0
 hum            757
 tempm          673
dtype: int64

In [ ]:
df.fillna(method='bfill',inplace=True)

In [ ]:
df.isnull().sum()

datetime_utc    0
 hum            0
 tempm          0
dtype: int64

In [ ]:
len(df)

100990

In [ ]:
df.columns

Index(['datetime_utc', ' hum', ' tempm'], dtype='object')

In [ ]:
df[' tempm'].dtype

dtype('float64')

In [ ]:
new_df= pd.DataFrame(columns=['date_month_year','hum','mean_temp'])
new_df

Empty DataFrame
Columns: [date_month_year, hum, mean_temp]
Index: []

In [ ]:
dtmt=df['datetime_utc'][0]
dtmt = dtmt[:8]
mean_temp=0
mean_humid=0
n=0
dtmt

'19961101'

In [ ]:
for i in range(len(df)):
    if dtmt == df.loc[i,'datetime_utc'][:8]:
      mean_temp+=df.loc[i,' tempm']
      mean_humid+=df.loc[i,' hum']
      n+=1
      #print(dtmt,df.loc[i,'datetime_utc'], mean_temp, mean_humid, n)
    else:
      new_df = new_df.append({'date_month_year':dtmt, 'mean_temp':round(mean_temp/n,2) ,'hum': round(mean_humid/n,2)}, ignore_index = True)
      n=1
      dtmt = df.loc[i,'datetime_utc'][:8]
      mean_temp=df.loc[i,' tempm']
      mean_humid=df.loc[i,' hum']

new_df = new_df.append({'date_month_year':dtmt, 'mean_temp':round(mean_temp/n,2) ,'hum': round(mean_humid/n,2)}, ignore_index = True)

In [ ]:
new_df.head()

  date_month_year    hum  mean_temp
0        19961101  52.92      22.33
1        19961102  48.62      22.92
2        19961103  55.96      21.79
3        19961104  48.06      22.72
4        19961105  29.40      27.80

In [ ]:
new_df.tail()

     date_month_year    hum  mean_temp
7334        20170420  27.50      34.50
7335        20170421  39.38      34.25
7336        20170422  40.90      32.90
7337        20170423  27.50      32.88
7338        20170424  27.14      32.00

In [ ]:
final_df= pd.DataFrame(columns=['year','month','hum','mean_temp'])
final_df

Empty DataFrame
Columns: [year, month, hum, mean_temp]
Index: []

In [ ]:
dtmt=new_df['date_month_year'][0]
dtmt = dtmt[:6]
mean_temp=0
mean_humid=0
n=0
dtmt

'199611'

In [ ]:
new_df.isnull().sum()

date_month_year    0
hum                0
mean_temp          0
dtype: int64

In [ ]:
for i in range(len(new_df)):
    if dtmt == new_df.loc[i,'date_month_year'][:6]:
      mean_temp+= round(new_df.loc[i,'mean_temp'],2)
      mean_humid+= round(new_df.loc[i,'hum'],2)
      mean_temp=round(mean_temp,2)
      mean_humid=round(mean_humid,2)
      n+=1
      #print(dtmt,new_df.loc[i,'date_month_year'], mean_temp, mean_humid, n)
      #print(new_df.loc[i,'mean_temp'],new_df.loc[i,'hum'])
    else:
      final_df = final_df.append({'year':dtmt[:4], 'month':dtmt[4:6],'mean_temp':round(mean_temp/n,2) ,'hum': round(mean_humid/n,2)}, ignore_index = True)
      n=1
      dtmt = new_df.loc[i,'date_month_year'][:6]
      mean_temp=new_df.loc[i,'mean_temp']
      mean_humid=new_df.loc[i,'hum']

final_df = final_df.append({'year':dtmt[:4], 'month':dtmt[4:6],'mean_temp':round(mean_temp/n,2) ,'hum': round(mean_humid/n,2)}, ignore_index = True)

In [ ]:
final_df.head()

   year month    hum  mean_temp
0  1996    11  47.92      19.55
1  1996    12  58.77      13.81
2  1997    01  75.87      12.83
3  1997    02  62.35      15.96
4  1997    03  61.66      21.26

In [ ]:
final_df.tail()

     year month    hum  mean_temp
240  2016    12  68.80      17.68
241  2017    01  77.21      15.71
242  2017    02  64.38      18.35
243  2017    03  48.01      23.75
244  2017    04  30.41      30.75

In [ ]:
final_df.isnull().sum()

year         0
month        0
hum          0
mean_temp    0
dtype: int64

In [ ]:
from google.colab import files

final_df.to_csv('temp_humid_processed.csv')
files.download('temp_humid_processed.csv')

In [ ]:
df=final_df

In [ ]:
df.head()

   year month    hum  mean_temp
0  1996    11  47.92      19.55
1  1996    12  58.77      13.81
2  1997    01  75.87      12.83
3  1997    02  62.35      15.96
4  1997    03  61.66      21.26

##For Temperature prediction

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIT Hackathon/temp_humid_delhi_processed.csv")

In [ ]:
X=df[['year','month']]
y=df['mean_temp']

In [ ]:
X.head()

   year  month
0  1996     11
1  1996     12
2  1997      1
3  1997      2
4  1997      3

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

## Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

li_model=LinearRegression()
li_model.fit(X_train,y_train)

y_pred=li_model.predict(X_test)

In [ ]:
accuracy=li_model.score(X_test,y_test)

In [ ]:
accuracy

0.01591692330619021

## Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print("RMSE: ", mse**(1/2.0))

MSE:  6.347214285714286
RMSE:  2.519367834539904

In [ ]:
accuracy=model.score(X_test,y_test)
accuracy

0.8819181277486975

##Bidirectional-LSTM

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIT Hackathon/temp_humid_processed.csv")

In [ ]:
df.drop(labels='Unnamed: 0',axis=1,inplace=True)
df.head()

   month_year    hum  mean_temp
0      199611  47.92      19.55
1      199612  58.77      13.81
2      199701  75.87      12.83
3      199702  62.35      15.96
4      199703  61.66      21.26

In [ ]:
X=df[['month_year']
y=df['mean_temp']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
train_data = pd.concat([X_train, y_train], axis=1, join='inner')
test_data = pd.concat([X_test, y_test], axis=1, join='inner')

In [ ]:
train_data.head()

     month_year  mean_temp
229      201601      15.14
209      201405      31.41
96       200412      15.46
168      201012      13.99
84       200312      15.12

In [ ]:
X_train.shape

(196,)

In [ ]:
y_train.shape

(196,)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional

In [ ]:
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(1)))
model.add(LSTM(50,return_sequences=True))
model.add(Bidirectional(LSTM(50)))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')

TypeError: ignored

#temp and humidity pred

In [73]:
import numpy as np # linear algebra
import pandas as pd

In [ ]:
import os
os.listdir('drive/MyDrive/TRI-NIT_hackathon')

['college_id', 'NIT Hackathon']

In [125]:
Bangalore=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Bangalore_1990_2022_BangaloreCity.csv')
Chennai=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Chennai_1990_2022_Madras.csv')
Delhi=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Delhi_NCR_1990_2022_Safdarjung.csv')
Lucknow=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Lucknow_1990_2022.csv')
Mumbai=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Mumbai_1990_2022_Santacruz.csv')
Rajasthan=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/Rajasthan_1990_2022_Jodhpur.csv')
Bhubhneshwar=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/weather_Bhubhneshwar_1990_2022.csv')
Rourkela=pd.read_csv('drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/Temperature_And_Precipitation_Cities_IN/weather_Rourkela_2021_2022.csv')

In [126]:
Bangalore['city-Name'] = 'Bangalore'
Chennai['city-Name'] = 'Chennai'
Delhi['city-Name'] = 'Delhi'
Lucknow['city-Name'] = 'Lucknow'
Mumbai['city-Name'] = 'Mumbai'
Rajasthan['city-Name'] = 'Rajasthan'
Bhubhneshwar['city-Name'] = 'Bhubhneshwar'
Rourkela['city-Name'] = 'Rourkela'

In [101]:
Lucknow

             time  tavg  tmin  tmax  prcp city-Name
0      01-01-1990   7.2   NaN  18.1   0.0   Lucknow
1      02-01-1990  10.5   NaN  17.2   0.0   Lucknow
2      03-01-1990  10.2   1.8  18.6   NaN   Lucknow
3      04-01-1990   9.1   NaN  19.3   0.0   Lucknow
4      05-01-1990  13.5   NaN  23.8   0.0   Lucknow
...           ...   ...   ...   ...   ...       ...
11889  21-07-2022  27.4  25.1  33.1  27.3   Lucknow
11890  22-07-2022  28.1  26.1  31.1  16.0   Lucknow
11891  23-07-2022  30.3  26.2  34.7  11.9   Lucknow
11892  24-07-2022  30.0  28.1  34.7   2.0   Lucknow
11893  25-07-2022  27.1  24.1  34.3   0.5   Lucknow

[11894 rows x 6 columns]

In [102]:
Mumbai

             time  tavg  tmin  tmax  prcp city-Name
0      01-01-1990  23.2  17.0   NaN   0.0    Mumbai
1      02-01-1990  22.2  16.5  29.9   0.0    Mumbai
2      03-01-1990  21.8  16.3  30.7   0.0    Mumbai
3      04-01-1990  25.4  17.9  31.8   0.0    Mumbai
4      05-01-1990  26.5  19.3  33.7   0.0    Mumbai
...           ...   ...   ...   ...   ...       ...
11889  21-07-2022  27.6  25.6  30.5  10.9    Mumbai
11890  22-07-2022  28.3  26.0  30.5   3.0    Mumbai
11891  23-07-2022  28.2  25.8  31.3   5.1    Mumbai
11892  24-07-2022  28.1  25.6  30.4   7.1    Mumbai
11893  25-07-2022  28.3  25.1  30.2   7.1    Mumbai

[11894 rows x 6 columns]

In [34]:
Rajasthan

             time  tavg  tmin  tmax  prcp  city-Name
0      01-01-1990  22.9  19.1  28.4   NaN  Rajasthan
1      02-01-1990  21.7   NaN  26.5   0.0  Rajasthan
2      03-01-1990  21.0  16.4  26.5   0.0  Rajasthan
3      04-01-1990  20.8   NaN  27.4   0.0  Rajasthan
4      05-01-1990  20.4  14.2  26.1   0.0  Rajasthan
...           ...   ...   ...   ...   ...        ...
11889  21-07-2022  23.7  20.5  30.8  82.5  Rajasthan
11890  22-07-2022  23.2  21.1  27.9   0.0  Rajasthan
11891  23-07-2022  23.1  20.9  26.7   0.0  Rajasthan
11892  24-07-2022  22.8  20.0  26.7   0.3  Rajasthan
11893  25-07-2022  24.1  20.2  28.5   0.5  Rajasthan

[11894 rows x 6 columns]

In [127]:
Bhubhneshwar.drop(['snow','wdir','wpgt','pres','tsun','wspd'],axis=1,inplace=True)

In [77]:
Bhubhneshwar

             time  tavg  tmin  tmax  prcp     city-Name
0      1990-01-01  20.1   NaN  28.0   0.0  Bhubhneshwar
1      1990-01-02  20.7  16.4   NaN   0.0  Bhubhneshwar
2      1990-01-03  20.7  16.0  27.4   0.0  Bhubhneshwar
3      1990-01-04  18.8   NaN  28.0   0.0  Bhubhneshwar
4      1990-01-05  19.8  11.0  28.2   0.0  Bhubhneshwar
...           ...   ...   ...   ...   ...           ...
11930  2022-08-31  29.2  26.3  33.0   9.0  Bhubhneshwar
11931  2022-09-01  29.6  27.0  33.0   2.1  Bhubhneshwar
11932  2022-09-02  29.7  26.3  33.0   3.3  Bhubhneshwar
11933  2022-09-03  29.2  26.1  34.0   9.7  Bhubhneshwar
11934  2022-09-04  27.6  25.9  31.6  12.8  Bhubhneshwar

[11935 rows x 6 columns]

In [128]:
Rourkela.drop(['snow','wdir','wpgt','pres','tsun','wspd'],axis=1,inplace=True)

In [79]:
Rourkela

           time  tavg  tmin  tmax  prcp city-Name
0    2021-07-06  29.3  26.2  32.6   NaN  Rourkela
1    2021-07-07  29.7  27.3  33.4  11.1  Rourkela
2    2021-07-08  27.4  25.8  29.7  66.9  Rourkela
3    2021-07-09  28.5  26.1  32.1  11.4  Rourkela
4    2021-07-10  29.0  26.2  32.6   2.7  Rourkela
..          ...   ...   ...   ...   ...       ...
421  2022-08-31  29.0  26.6  33.5   2.0  Rourkela
422  2022-09-01  29.1  25.7  33.2  11.5  Rourkela
423  2022-09-02  29.4  26.4  33.7   1.5  Rourkela
424  2022-09-03  28.7  26.6  32.6   8.0  Rourkela
425  2022-09-04  28.2  25.9  31.8  17.7  Rourkela

[426 rows x 6 columns]

In [39]:
Delhi

             time  tavg  tmin  tmax  prcp city-Name
0      01-01-1990   9.4   6.0  15.1   0.0     Delhi
1      02-01-1990   9.3   5.2  14.2   0.0     Delhi
2      03-01-1990   9.0   6.5  13.6   0.0     Delhi
3      04-01-1990  10.7   6.0  17.5   0.0     Delhi
4      05-01-1990  12.6   7.3  20.8   0.0     Delhi
...           ...   ...   ...   ...   ...       ...
11889  21-07-2022  28.6  26.8  30.6  21.2     Delhi
11890  22-07-2022  29.3  27.0  32.9   0.3     Delhi
11891  23-07-2022  30.1  25.5  34.9   8.9     Delhi
11892  24-07-2022  30.6  27.1  35.7   0.0     Delhi
11893  25-07-2022  30.7  26.8  35.7   0.0     Delhi

[11894 rows x 6 columns]

In [40]:
Chennai

             time  tavg  tmin  tmax  prcp city-Name
0      01-01-1990  25.2  22.8  28.4   0.5   Chennai
1      02-01-1990  24.9  21.7  29.1   0.0   Chennai
2      03-01-1990  25.6  21.4  29.8   0.0   Chennai
3      04-01-1990  25.7   NaN  28.7   0.0   Chennai
4      05-01-1990  25.5  20.7  28.4   0.0   Chennai
...           ...   ...   ...   ...   ...       ...
11889  21-07-2022  28.4  24.5  32.8  21.1   Chennai
11890  22-07-2022  27.8  24.6  32.2  22.1   Chennai
11891  23-07-2022  27.4  24.7  32.6  18.6   Chennai
11892  24-07-2022  27.8  25.0  33.3   9.1   Chennai
11893  25-07-2022  28.1  25.4  32.6   2.9   Chennai

[11894 rows x 6 columns]

In [41]:
Bangalore

             time  tavg  tmin  tmax  prcp  city-Name
0      01-01-1990  22.9  19.1  28.4   NaN  Bangalore
1      02-01-1990  21.7   NaN  26.5   0.0  Bangalore
2      03-01-1990  21.0  16.4  26.5   0.0  Bangalore
3      04-01-1990  20.8   NaN  27.4   0.0  Bangalore
4      05-01-1990  20.4  14.2  26.1   0.0  Bangalore
...           ...   ...   ...   ...   ...        ...
11889  21-07-2022  23.7  20.5  30.8  82.5  Bangalore
11890  22-07-2022  23.2  21.1  27.9   0.0  Bangalore
11891  23-07-2022  23.1  20.9  26.7   0.0  Bangalore
11892  24-07-2022  22.8  20.0  26.7   0.3  Bangalore
11893  25-07-2022  24.1  20.2  28.5   0.5  Bangalore

[11894 rows x 6 columns]

In [129]:
def clean(df):
    df['prcp'].fillna(method="ffill",inplace=True)
    df['tmin'].fillna(method="ffill",inplace=True)
    df['tmax'].fillna(method="ffill",inplace=True)
    return df

In [130]:
Chennai=clean(Chennai)
Bangalore=clean(Bangalore)
Delhi=clean(Delhi)
Lucknow=clean(Lucknow)
Mumbai=clean(Mumbai)
Rajasthan=clean(Rajasthan)
Bhubhneshwar=clean(Bhubhneshwar)
Rourkela=clean(Rourkela)

In [131]:
Chennai['target']=Chennai.shift(-1)['tmax']
Bangalore['target']=Bangalore.shift(-1)['tmax']
Delhi['target']=Delhi.shift(-1)['tmax']
Lucknow['target']=Lucknow.shift(-1)['tmax']
Mumbai['target']=Mumbai.shift(-1)['tmax']
Rajasthan['target']=Rajasthan.shift(-1)['tmax']
Bhubhneshwar['target']=Bhubhneshwar.shift(-1)['tmax']
Rourkela['target']=Rourkela.shift(-1)['tmax']

In [108]:
Chennai.isnull().sum()

time          0
tavg         27
tmin          0
tmax          0
prcp          0
city-Name     0
target        1
dtype: int64

In [132]:
frames = [Chennai, Bangalore,Delhi,Lucknow,Mumbai,Rajasthan,Bhubhneshwar,Rourkela]
df = pd.concat(frames)

In [85]:
Rourkela

           time  tavg  tmin  tmax  prcp city-Name  target
0    2021-07-06  29.3  26.2  32.6   NaN  Rourkela    33.4
1    2021-07-07  29.7  27.3  33.4  11.1  Rourkela    29.7
2    2021-07-08  27.4  25.8  29.7  66.9  Rourkela    32.1
3    2021-07-09  28.5  26.1  32.1  11.4  Rourkela    32.6
4    2021-07-10  29.0  26.2  32.6   2.7  Rourkela    33.7
..          ...   ...   ...   ...   ...       ...     ...
421  2022-08-31  29.0  26.6  33.5   2.0  Rourkela    33.2
422  2022-09-01  29.1  25.7  33.2  11.5  Rourkela    33.7
423  2022-09-02  29.4  26.4  33.7   1.5  Rourkela    32.6
424  2022-09-03  28.7  26.6  32.6   8.0  Rourkela    31.8
425  2022-09-04  28.2  25.9  31.8  17.7  Rourkela     NaN

[426 rows x 7 columns]

In [86]:
df.shape

(83725, 7)

In [110]:
df.isnull().sum()

time           0
tavg         490
tmin           3
tmax           1
prcp           3
city-Name      0
target         8
dtype: int64

In [111]:
df.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            416, 417, 418, 419, 420, 421, 422, 423, 424, 425],
           dtype='int64', length=83725)

In [133]:
df.reset_index()

       index        time  tavg  tmin  tmax  prcp city-Name  target
0          0  01-01-1990  25.2  22.8  28.4   0.5   Chennai    29.1
1          1  02-01-1990  24.9  21.7  29.1   0.0   Chennai    29.8
2          2  03-01-1990  25.6  21.4  29.8   0.0   Chennai    28.7
3          3  04-01-1990  25.7  21.4  28.7   0.0   Chennai    28.4
4          4  05-01-1990  25.5  20.7  28.4   0.0   Chennai    26.1
...      ...         ...   ...   ...   ...   ...       ...     ...
83720    421  2022-08-31  29.0  26.6  33.5   2.0  Rourkela    33.2
83721    422  2022-09-01  29.1  25.7  33.2  11.5  Rourkela    33.7
83722    423  2022-09-02  29.4  26.4  33.7   1.5  Rourkela    32.6
83723    424  2022-09-03  28.7  26.6  32.6   8.0  Rourkela    31.8
83724    425  2022-09-04  28.2  25.9  31.8  17.7  Rourkela     NaN

[83725 rows x 8 columns]

In [134]:
df['city-Name']=df['city-Name'].map({'Chennai': '0', 'Bangalore': '1','Delhi':'2','Lucknow':'3','Mumbai':'4','Rajasthan':'5','Bhubhneshwar':'6','Rourkela':'7'})

In [114]:
df

           time  tavg  tmin  tmax  prcp city-Name  target
0    01-01-1990  25.2  22.8  28.4   0.5         0    29.1
1    02-01-1990  24.9  21.7  29.1   0.0         0    29.8
2    03-01-1990  25.6  21.4  29.8   0.0         0    28.7
3    04-01-1990  25.7  21.4  28.7   0.0         0    28.4
4    05-01-1990  25.5  20.7  28.4   0.0         0    26.1
..          ...   ...   ...   ...   ...       ...     ...
421  2022-08-31  29.0  26.6  33.5   2.0         7    33.2
422  2022-09-01  29.1  25.7  33.2  11.5         7    33.7
423  2022-09-02  29.4  26.4  33.7   1.5         7    32.6
424  2022-09-03  28.7  26.6  32.6   8.0         7    31.8
425  2022-09-04  28.2  25.9  31.8  17.7         7     NaN

[83725 rows x 7 columns]

In [135]:
print(df)
df[["day", "month", "year"]] = df["time"].str.split("-", expand = True)
print("\nNew DataFrame:")
df

           time  tavg  tmin  tmax  prcp city-Name  target
0    01-01-1990  25.2  22.8  28.4   0.5         0    29.1
1    02-01-1990  24.9  21.7  29.1   0.0         0    29.8
2    03-01-1990  25.6  21.4  29.8   0.0         0    28.7
3    04-01-1990  25.7  21.4  28.7   0.0         0    28.4
4    05-01-1990  25.5  20.7  28.4   0.0         0    26.1
..          ...   ...   ...   ...   ...       ...     ...
421  2022-08-31  29.0  26.6  33.5   2.0         7    33.2
422  2022-09-01  29.1  25.7  33.2  11.5         7    33.7
423  2022-09-02  29.4  26.4  33.7   1.5         7    32.6
424  2022-09-03  28.7  26.6  32.6   8.0         7    31.8
425  2022-09-04  28.2  25.9  31.8  17.7         7     NaN

[83725 rows x 7 columns]

New DataFrame:

           time  tavg  tmin  tmax  prcp city-Name  target   day month  year
0    01-01-1990  25.2  22.8  28.4   0.5         0    29.1    01    01  1990
1    02-01-1990  24.9  21.7  29.1   0.0         0    29.8    02    01  1990
2    03-01-1990  25.6  21.4  29.8   0.0         0    28.7    03    01  1990
3    04-01-1990  25.7  21.4  28.7   0.0         0    28.4    04    01  1990
4    05-01-1990  25.5  20.7  28.4   0.0         0    26.1    05    01  1990
..          ...   ...   ...   ...   ...       ...     ...   ...   ...   ...
421  2022-08-31  29.0  26.6  33.5   2.0         7    33.2  2022    08    31
422  2022-09-01  29.1  25.7  33.2  11.5         7    33.7  2022    09    01
423  2022-09-02  29.4  26.4  33.7   1.5         7    32.6  2022    09    02
424  2022-09-03  28.7  26.6  32.6   8.0         7    31.8  2022    09    03
425  2022-09-04  28.2  25.9  31.8  17.7         7     NaN  2022    09    04

[83725 rows x 10 columns]

In [136]:
df.drop(labels=['prcp', 'day','time','tmin', 'tmax','tavg' ],axis=1,inplace=True)

In [137]:
df.head()

  city-Name  target month  year
0         0    29.1    01  1990
1         0    29.8    01  1990
2         0    28.7    01  1990
3         0    28.4    01  1990
4         0    26.1    01  1990

In [138]:
df.tail()

    city-Name  target month year
421         7    33.2    08   31
422         7    33.7    09   01
423         7    32.6    09   02
424         7    31.8    09   03
425         7     NaN    09   04

In [139]:
df=df.dropna()

In [140]:
df.isnull().sum()

city-Name    0
target       0
month        0
year         0
dtype: int64

In [143]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [144]:
X = df.drop("target", axis=1)
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [151]:
y.head()

0    29.1
1    29.8
2    28.7
3    28.4
4    26.1
Name: target, dtype: float64

In [145]:
regressor = RandomForestRegressor(n_estimators=100, random_state=42)
regressor.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = regressor.predict(X_test)

# Calculate the mean squared error

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error: ", mse)
print("R-Squared Score: ", r2)

Mean Squared Error:  4.27624363897551
R-Squared Score:  0.7928141125031133

In [146]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print("RMSE: ", mse**(1/2.0))

MSE:  4.27624363897551
RMSE:  2.067908034457894

In [147]:
accuracy=regressor.score(X_test,y_test)
accuracy

0.7928141125031133

In [159]:
y_predict=regressor.predict([[7,8,2023]])
y_predict[0]

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

31.18182402259531

In [154]:
import pickle
# Dump the trained classifier with Pickle
RF_pkl_filename = '/content/drive/MyDrive/TRI-NIT_hackathon/NIT Hackathon/temp_pred.pkl'
# Open the file to save as pkl file
RF_Model_pkl = open(RF_pkl_filename, 'wb')
pickle.dump(regressor, RF_Model_pkl)
# Close the pickle instances
RF_Model_pkl.close()